# Generated by Django 4.0.6 on 2022-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(blank=True, default='Click Link To Read Blog Post', max_length=255, null=True),
        ),
    ]
