# Generated by Django 4.0.6 on 2022-08-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0002_alter_post_dislikes_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
