# Generated by Django 4.0.6 on 2022-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0005_remove_post_post_time_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
