# Generated by Django 4.0.6 on 2022-08-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0002_rename_header_image_post_image'),
        ('startblog', '0007_post_downvotes_post_upvotes'),
    ]

    operations = [
    ]
