# Generated by Django 4.0.6 on 2022-08-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0012_alter_post_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
    ]
