# Generated by Django 4.0.6 on 2022-08-21 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0016_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photo/'),
            preserve_default=False,
        ),
    ]
