# Generated by Django 4.0.6 on 2022-08-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0017_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
