# Generated by Django 4.0.6 on 2022-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0020_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
