# Generated by Django 4.0.6 on 2022-08-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0021_remove_post_body_post_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
