# Generated by Django 4.0.5 on 2022-09-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0022_remove_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
