# Generated by Django 4.0.5 on 2022-09-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0023_remove_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
